### ISSUE TITLE
npm install hangs on @icons/material extracting

### ISSUE THREAD

**Issue by standbyoneself** [SVG-Edit/svg-edit-react#1]
<img width="1440" alt="Screenshot 2021-01-27 at 15 23 22" src="https://user-images.githubusercontent.com/57719759/105991094-70eea580-60b4-11eb-8866-7cc501e233ef.png">

Waiting for 10 minutes has changed nothing.

Any help?

**Comment by brettz9** [comment]
You might look at the `run-if-changed` field in `package.json`. `run-if-changed` is intended to help force commands when files change, such as an npm install when there is a new commit with a change to the package-lock.

So I think there could be some recursion if a changed file (e.g., as we have had in the main branch for `package-lock.json`) causes an install (esp. if there is also a `prepare` script). I'm not working with the code now, so can't really say more about whether it applies, but wanted to mention in case that's what was going on.

**Comment by jfhenon** [comment]
not sure. can you rebuild node_modules from scratch with npm ci?

**Comment by jfhenon** [comment]
I believe I found the issue. You have a wrong .npmrc (that was required when the repo was private). 
I deleted it, rebuild the package and this seems to work... 
Let me know if this is OK for you.
