### ISSUE TITLE
new version svg edit react ?

### ISSUE THREAD

**Issue by patsonkaushik** [SVG-Edit/svg-edit-react#3]

**Comment by jfhenon** [comment]
yes, should arrive...

**Comment by Candymanspoken** [comment]
> yes, should arrive...

When
<details><summary>Details</summary>
<p>



</p>
</details>

**Comment by sabeerbikba** [comment]
Hi @SVG-Edit,

Thank you for your work on this project. Could you please update the code to be compatible with the latest version of React? This would help ensure continued usability and take advantage of the latest features and improvements.
